from django.urls import path

from .startup_ai_views import (
    StartupAiCoachReplyView,
    StartupAiInnovationPackView,
    StartupAiQuestionnaireView,
    StartupAiTwentyCriteriaView,
)
from .device_pairing_views import (
    DevicePairConfirmView,
    DevicePairCreateView,
    DevicePairStatusView,
)
from .education_ai_views import EducationAiCompletionView
from .presentation_views import (
    TopicPresentationDetailView,
    TopicPresentationFileView,
    TopicPresentationListCreateView,
)
from .handout_views import TopicHandoutDetailView, TopicHandoutFileView, TopicHandoutListCreateView
from .syllabus_catalog_views import (
    AdminCourseSyllabusDetailView,
    AdminCourseSyllabusListCreateView,
    CourseSyllabusCatalogView,
    StaffCourseSelectionDetailView,
    StaffCourseSelectionListView,
)
from .content_catalog_views import (
    ContentCatalogDetailView,
    ContentCatalogListView,
    ContentCatalogSubjectsView,
)
from .migrate_views import MigrateFullExportView
from .staff_profile_views import StaffAvatarView
from .views import (
    AdminCampusBuildingDetailView,
    AdminCampusBuildingListCreateView,
    AdminStaffLocationAlertsView,
    AdminStaffLocationPingsView,
    AdminStaffScheduleBulkView,
    AdminStaffScheduleDetailView,
    AdminStaffScheduleListCreateView,
    AuthMeView,
    HealthView,
    LiveTestPublicRetrieveView,
    LiveTestDraftUpsertView,
    LiveTestFinalizeView,
    LiveTestSubmissionView,
    LiveTestUpsertView,
    AdminDeprovisionStaffView,
    AdminProvisionStaffView,
    ChangePasswordView,
    LocalLoginView,
    PreparedContentV1DetailView,
    PreparedContentV1View,
    PreparedContentView,
    StaffLocationPingView,
    ScheduleWeekInfoView,
    StaffCampusBuildingListView,
    StaffScheduleSelfView,
    StartupApplicationAdminInboxView,
    StartupApplicationDetailView,
    StartupApplicationListCreateView,
    StartupApplicationSubmitView,
    SyllabusDocumentDestroyView,
    SyllabusDocumentListCreateView,
)

urlpatterns = [
    path('v1/content-catalog/', ContentCatalogListView.as_view(), name='content-catalog-list'),
    path('v1/content-catalog/subjects/', ContentCatalogSubjectsView.as_view(), name='content-catalog-subjects'),
    path('v1/content-catalog/<int:pk>/', ContentCatalogDetailView.as_view(), name='content-catalog-detail'),
    path('v1/migrate/full-export/', MigrateFullExportView.as_view(), name='migrate-full-export'),
    path('health/', HealthView.as_view(), name='health'),
    path('prepared-content/', PreparedContentView.as_view(), name='prepared-content'),
    path('v1/prepared-content/', PreparedContentV1View.as_view(), name='prepared-content-v1'),
    path('v1/prepared-content/<int:pk>/', PreparedContentV1DetailView.as_view(), name='prepared-content-v1-detail'),
    path('v1/syllabuses/', SyllabusDocumentListCreateView.as_view(), name='syllabuses'),
    path('v1/syllabuses/<int:pk>/', SyllabusDocumentDestroyView.as_view(), name='syllabus-detail'),
    path('v1/admin/course-syllabuses/', AdminCourseSyllabusListCreateView.as_view(), name='admin-course-syllabuses'),
    path('v1/admin/course-syllabuses/<int:pk>/', AdminCourseSyllabusDetailView.as_view(), name='admin-course-syllabus-detail'),
    path('v1/course-syllabuses/catalog/', CourseSyllabusCatalogView.as_view(), name='course-syllabus-catalog'),
    path('v1/course-syllabuses/my/', StaffCourseSelectionListView.as_view(), name='staff-course-selections'),
    path('v1/course-syllabuses/my/<int:syllabus_id>/', StaffCourseSelectionDetailView.as_view(), name='staff-course-selection-detail'),
    path('v1/live-tests/', LiveTestUpsertView.as_view(), name='live-tests-upsert'),
    path('v1/live-tests/<str:session_key>/', LiveTestPublicRetrieveView.as_view(), name='live-tests-public'),
    path('v1/live-tests/<str:session_key>/drafts/', LiveTestDraftUpsertView.as_view(), name='live-tests-drafts'),
    path('v1/live-tests/<str:session_key>/finalize/', LiveTestFinalizeView.as_view(), name='live-tests-finalize'),
    path('v1/live-tests/<str:session_key>/submissions/', LiveTestSubmissionView.as_view(), name='live-tests-submissions'),
    path('v1/auth/me/', AuthMeView.as_view(), name='auth-me'),
    path('v1/auth/me/avatar/', StaffAvatarView.as_view(), name='auth-me-avatar'),
    path('v1/auth/local-login/', LocalLoginView.as_view(), name='auth-local-login'),
    path('v1/auth/change-password/', ChangePasswordView.as_view(), name='auth-change-password'),
    path('v1/auth/admin-provision-staff/', AdminProvisionStaffView.as_view(), name='auth-admin-provision-staff'),
    path('v1/auth/admin-deprovision-staff/', AdminDeprovisionStaffView.as_view(), name='auth-admin-deprovision-staff'),
    path('v1/device-pair/create/', DevicePairCreateView.as_view(), name='device-pair-create'),
    path('v1/device-pair/confirm/', DevicePairConfirmView.as_view(), name='device-pair-confirm'),
    path('v1/device-pair/status/<str:pairing_token>/', DevicePairStatusView.as_view(), name='device-pair-status'),
    path('v1/education-ai/completion/', EducationAiCompletionView.as_view(), name='education-ai-completion'),
    path('v1/presentations/', TopicPresentationListCreateView.as_view(), name='presentations-list-create'),
    path('v1/presentations/<int:pk>/file/', TopicPresentationFileView.as_view(), name='presentation-file'),
    path('v1/presentations/<int:pk>/', TopicPresentationDetailView.as_view(), name='presentation-detail'),
    path('v1/handouts/', TopicHandoutListCreateView.as_view(), name='handouts-list-create'),
    path('v1/handouts/<int:pk>/file/', TopicHandoutFileView.as_view(), name='handout-file'),
    path('v1/handouts/<int:pk>/', TopicHandoutDetailView.as_view(), name='handout-detail'),
    path('v1/startup-ai/questionnaire/', StartupAiQuestionnaireView.as_view(), name='startup-ai-questionnaire'),
    path('v1/startup-ai/twenty-criteria/', StartupAiTwentyCriteriaView.as_view(), name='startup-ai-twenty-criteria'),
    path('v1/startup-ai/innovation-pack/', StartupAiInnovationPackView.as_view(), name='startup-ai-innovation-pack'),
    path('v1/startup-ai/coach-reply/', StartupAiCoachReplyView.as_view(), name='startup-ai-coach-reply'),
    path('v1/startup-applications/', StartupApplicationListCreateView.as_view(), name='startup-applications'),
    path('v1/startup-applications/admin/inbox/', StartupApplicationAdminInboxView.as_view(), name='startup-admin-inbox'),
    path('v1/startup-applications/<int:pk>/', StartupApplicationDetailView.as_view(), name='startup-application-detail'),
    path('v1/startup-applications/<int:pk>/submit/', StartupApplicationSubmitView.as_view(), name='startup-application-submit'),
    path('v1/staff/location-ping/', StaffLocationPingView.as_view(), name='staff-location-ping'),
    path('v1/staff/schedule/', StaffScheduleSelfView.as_view(), name='staff-schedule-self'),
    path('v1/staff/schedule-week-info/', ScheduleWeekInfoView.as_view(), name='staff-schedule-week-info'),
    path('v1/staff/buildings/', StaffCampusBuildingListView.as_view(), name='staff-buildings'),
    path('v1/admin/campus-buildings/', AdminCampusBuildingListCreateView.as_view(), name='admin-campus-buildings'),
    path('v1/admin/campus-buildings/<int:pk>/', AdminCampusBuildingDetailView.as_view(), name='admin-campus-building-detail'),
    path('v1/admin/staff-schedule/bulk/', AdminStaffScheduleBulkView.as_view(), name='admin-staff-schedule-bulk'),
    path('v1/admin/staff-schedule/', AdminStaffScheduleListCreateView.as_view(), name='admin-staff-schedule'),
    path('v1/admin/staff-schedule/<int:pk>/', AdminStaffScheduleDetailView.as_view(), name='admin-staff-schedule-detail'),
    path('v1/admin/staff-location-pings/', AdminStaffLocationPingsView.as_view(), name='admin-staff-location-pings'),
    path('v1/admin/staff-location-alerts/', AdminStaffLocationAlertsView.as_view(), name='admin-staff-location-alerts'),
]
