# Generated by Django 6.0.4 on 2026-04-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=128)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('topic', models.CharField(max_length=255)),
                ('topic_norm', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_key', 'kind', 'topic_norm', '-created_at'], name='core_prepar_owner_k_485e70_idx')],
            },
        ),
    ]
