# Generated by Django 6.0.4 on 2026-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparedcontent',
            name='kind',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('presentation', 'Presentation'), ('case', 'Case'), ('test', 'Test')], db_index=True, max_length=32),
        ),
    ]
