# Generated by Django 6.0.4 on 2026-05-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_preparedcontent_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=128)),
                ('external_id', models.CharField(max_length=128)),
                ('file_name', models.CharField(max_length=512)),
                ('topics', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_key', '-created_at'], name='core_syllab_owner_k_01ad70_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner_key', 'external_id'), name='core_syllabus_owner_external_uniq')],
            },
        ),
    ]
