# Generated by Django 6.0.4 on 2026-05-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_live_test_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('participant_kind', models.CharField(default='student', max_length=16)),
                ('profile_snapshot', models.JSONField(default=dict)),
                ('ai_pack', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner_key', '-updated_at'], name='core_startu_owner_k_0ea1c2_idx'), models.Index(fields=['status', '-submitted_at'], name='core_startu_status_0e664a_idx')],
            },
        ),
    ]
