# Generated by Django 6.0.4 on 2026-05-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_startup_project_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprojectapplication',
            name='submission_dossier',
            field=models.JSONField(default=dict),
        ),
    ]
