# Generated by Django 6.0.4 on 2026-05-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_startup_submission_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprojectapplication',
            name='project_domain',
            field=models.CharField(db_index=True, default='startup', max_length=20),
        ),
        migrations.AddField(
            model_name='startupprojectapplication',
            name='workspace_profile',
            field=models.JSONField(default=dict),
        ),
    ]
