# Generated by Django 6.0.4 on 2026-05-04 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_startup_domain_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_ts_ms', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['owner_key', '-recorded_at'], name='core_staffl_owner_k_b7646f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=128)),
                ('weekday', models.SmallIntegerField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('building_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=1000)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['owner_key', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['owner_key', 'weekday', 'is_active'], name='core_staffs_owner_k_5ed10f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffLocationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=128)),
                ('building_name', models.CharField(blank=True, max_length=255)),
                ('expected_lat', models.FloatField()),
                ('expected_lng', models.FloatField()),
                ('actual_lat', models.FloatField()),
                ('actual_lng', models.FloatField()),
                ('distance_m', models.FloatField()),
                ('radius_m', models.PositiveIntegerField()),
                ('slot_start', models.TimeField(blank=True, null=True)),
                ('slot_end', models.TimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.staffscheduleslot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_key', '-created_at'], name='core_staffl_owner_k_92fe29_idx')],
            },
        ),
    ]
