# Generated by Django 6.0.4 on 2026-05-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_staff_location_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffscheduleslot',
            options={'ordering': ['owner_key', 'week_phase', 'weekday', 'start_time']},
        ),
        migrations.AddField(
            model_name='staffscheduleslot',
            name='week_phase',
            field=models.CharField(choices=[('every', 'Har hafta'), ('upper', 'Yuqori hafta (ISO toq)'), ('lower', 'Pastki hafta (ISO juft)')], db_index=True, default='every', max_length=16),
        ),
        migrations.AddIndex(
            model_name='staffscheduleslot',
            index=models.Index(fields=['owner_key', 'week_phase', 'weekday', 'is_active'], name='core_staffs_owner_k_bd959c_idx'),
        ),
    ]
