# Generated by Django 6.0.4 on 2026-05-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_staff_schedule_week_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=1000)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order', 'name'], name='core_campus_is_acti_23e0d3_idx')],
            },
        ),
        migrations.AddField(
            model_name='staffscheduleslot',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to='core.campusbuilding'),
        ),
    ]
