# Generated by Django 6.0.4 on 2026-06-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_clinical_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetestsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livetestsession',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='livetestsubmission',
            name='participant_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='LiveTestDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_key', models.CharField(db_index=True, max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('last_name', models.CharField(blank=True, default='', max_length=128)),
                ('answers', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='core.livetestsession')),
            ],
            options={
                'verbose_name': 'Test draft',
                'verbose_name_plural': 'Test draftlari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='livetestdraft',
            constraint=models.UniqueConstraint(fields=('session', 'participant_key'), name='uniq_live_test_draft_participant'),
        ),
    ]
