# Generated by Django 6.0.4 on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_live_test_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedcontent',
            name='author_display_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='preparedcontent',
            name='subject_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='preparedcontent',
            name='subject_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
